/* eslint-disable import/prefer-default-export */
/* Populated by react-webpack-redux:action */
export const API_CLEAR = 'API_CLEAR';
export const API_GET = 'API_GET';
export const API_QUERY = 'API_QUERY';
export const API_REMOVE = 'API_REMOVE';
export const API_SAVE = 'API_SAVE';
export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';
export const ROUTER_GO_TO = 'ROUTER_GO_TO';
export const VIEW_FILTER_LIST = 'VIEW_FILTER_LIST';
export const VIEW_FILTER_TABLE = 'VIEW_FILTER_TABLE';
export const VIEW_FILTER_GRID = 'VIEW_FILTER_GRID';
export const HEADERS_CONTROLS_SET = 'HEADERS_CONTROLS_SET';
export const HEADERS_CONTROLS_RESET = 'HEADERS_CONTROLS_RESET';
export const TOOLBAR_SHOW = 'TOOLBAR_SHOW';
export const TOOLBAR_HIDE = 'TOOLBAR_HIDE';
export const SEARCH_SET_QUERY = 'SEARCH_SET_QUERY';
export const BOOKS_LIST = 'BOOKS_LIST';
export const BOOKS_SET_LIST = 'BOOKS_SET_LIST';